require 'georgia_recipes/base'

# require 'georgia_recipes/apache'
# require 'georgia_recipes/assets'
# require 'georgia_recipes/backup'
# require 'georgia_recipes/carrierwave'
require 'georgia_recipes/chef'
# require 'georgia_recipes/elasticsearch'
# require 'georgia_recipes/errbit'
require 'georgia_recipes/georgia'
require 'georgia_recipes/imagemagick'
require 'georgia_recipes/memcached'
# require 'georgia_recipes/mongodb'
require 'georgia_recipes/monit'
# require 'georgia_recipes/mysql'
require 'georgia_recipes/newrelic'
require 'georgia_recipes/nginx'
# require 'georgia_recipes/nodejs'
require 'georgia_recipes/postgresql'
require 'georgia_recipes/rbenv'
# require 'georgia_recipes/redis'
# require 'georgia_recipes/sidekiq'
require 'georgia_recipes/solr'
require 'georgia_recipes/unicorn'